# -*- coding: utf-8 -*-
"""aula00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/clovesrocha/MiniCursoIP/blob/master/aula00.ipynb
"""

# ESCREVA AQUI SEU COMENTÁRIO...
# UNINASSAU
# DOCENTE: PROF. MSc Cloves
# ESTUDANTE:

#print('Olá mundo!')
c = True
print(type(c))