# -*- coding: utf-8 -*-
"""Ep. #01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/clovesrocha/minicursoip/blob/master/Ep_01.ipynb

Tutorial de Python
"""

# UNINASSAU - GRAÇAS
# PROF. MSc Cloves
# CC 4MB A301 de 7h30 às 10 (quinta)
# SI 2MA A205 de 10h às 12h40 (quinta)

print("Olá estudantes, bom dia!")