# -*- coding: utf-8 -*-
"""introd_flask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kc7FjLoaLvibRDPli2_B8Y7frCcRNyE2
"""

from flask import Flask
app = Flask(__name__)

@app.route('/')
def index():
 return '<h1>Hello World!</h1>'

