# Generated by Django 4.2.6 on 2023-10-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('idade', models.IntegerField(default=0)),
                ('foto', models.ImageField(upload_to='foto de perfil')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
